namespace EasySaveV2corrigé.Properties
{
    // These attributes indicate that this class is auto-generated by the Settings Designer in Visual Studio.
    // CompilerGenerated: Indicates that the class is generated by the compiler.
    // GeneratedCode: Specifies the tool and version used to generate the code.
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    // This class is a sealed partial class, meaning it cannot be inherited and its definition can be split across multiple files.
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        // This static field holds the default instance of the Settings class.
        // Synchronized ensures that the instance is thread-safe.
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        // This static property provides access to the default instance of the Settings class.
        // It allows you to access the application settings from anywhere in your code.
        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
